### ISSUE TITLE
problem with cancer_code without non_cancer code for the get_selfrep_illness function

### ISSUE THREAD

**Issue by LauricF** [lcpilling/ukbrapR#11]
Hi Luke,

in the function _get_selfrep_illness_ an error is returned when only a list of cancer_code is provided;
this is due to the code lines 81-87.

```
# join tables
	if (!is.null(ukb_dat_cancer_long))  ukb_dat_sr <- ukb_dat_cancer_long
	if (is.null(ukb_dat_sr))  {
		ukb_dat_sr <- ukb_dat_noncancer_long
	} else {
		ukb_dat_sr <- dplyr::full_join(ukb_dat_sr, ukb_dat_noncancer_long, by = c("eid"="eid", "instance"="instance"))
	}
```
When _ukb_dat_noncancer_long_ is null and _ukb_dat_cancer_long_ is not null the following line is run:
`ukb_dat_sr <- dplyr::full_join(ukb_dat_sr, ukb_dat_noncancer_long, by = c("eid"="eid", "instance"="instance"))` which return an error.

A fix could be:

```
# join tables
        if (!is.null(ukb_dat_cancer_long) & !is.null(ukb_dat_sr)){ # check that the two dataframes are non NULL
ukb_dat_sr <- dplyr::full_join(ukb_dat_sr, ukb_dat_noncancer_long, by = c("eid"="eid", "instance"="instance"))} else{
	if (!is.null(ukb_dat_cancer_long)){  # if only ukb_dat_cancer_long is non NULL
ukb_dat_sr <- ukb_dat_cancer_long
} else{  # if only ukb_dat_noncancer_long is non NULL
		ukb_dat_sr <- ukb_dat_noncancer_long}
```

thank you again,
Lauric

**Comment by lcpilling** [comment]
Thanks @LauricF! My PR #12 should fix this. Could you install and check?

`remotes::install_github("lcpilling/ukbrapR#12")`

I fixed another issue whilst there I noticed if providing both cancer/noncancer codes

**Comment by LauricF** [comment]
Thank you Luke,

The update version works, thank you @Simon-Leyss for checking it.
