### ISSUE TITLE
get_rap_phenos

### ISSUE THREAD

**Issue by arborzhang** [lcpilling/ukbrapR#14]
Hi Luke, thank you so much for developing the package.
I encountered an issue while attempting to extract phenotype data using the following command:
# get phenotype data (participant ID, sex, baseline age, and baseline assessment date)
ukb <- ukbrapR:::get_rap_phenos(c("eid", "p31", "p21003_i0", "p53_i0"))

Unfortunately, I received the error message below, regardless of whether I opted to create a Python environment or not:
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'dxdata'

I’m wondering if I might have missed some steps in the setup process. My main objective is to combine the phenotype data with previously extracted disease information.

Your guidance or suggestions would be greatly appreciated.

Thank you in advance for your help.

Best,
Evelyn

**Comment by lcpilling** [comment]
Hi Evelyn,

Did you launch a Spark cluster? This function only works there!

I should add that I do not plan on updating the Spark-based functions. I now much prefer to work in "normal" RStudio clusters on exported data! I recommend using the table exporter to export the variables you want and then loading in that way. I think it is actually faster and far cheaper than using JupyterLab Spark clusters (plus you get RStudio, yay)

Luke

**Comment by arborzhang** [comment]
Thank you so much for the quick response! It seems the issue is related to
the Python environment, as you mentioned. I will try using the table
exporter to export the variables instead.

I appreciate your kind help :)
