### ISSUE TITLE
need to have get_canreg = TRUE to be able to use ICD10 in hesin_diag

### ISSUE THREAD

**Issue by LauricF** [lcpilling/ukbrapR#8]
Hi Luke,

Thank you for adding the option to use ICD9 code. I am looking forward to use it.

I tried to rerun my code with the updated package and the run returned _diagnosis_list$hesin_diag_ as _NULL_ 
I only used an ICD10 code and no cancer code.

I think the reason is a small mistake in the get_diagnoses.R function  lines 327 to 385:
the code to extract the hesin_diag data is only run if the condition _get_canreg_ is _TRUE_.

Kind regards,
Lauric

**Comment by lcpilling** [comment]
Hi Lauric,

Thanks again for spotting this. I moved the HES ICD10 code block below the cancer registry code, but acctidently put it within the `if (get_canreg)  { }` condition curly brackets 🤦 oops. 

I have created a PR #9 with this fix. Can you check by installing:

```r
remotes::install_github("lcpilling/ukbrapR#9")
```

And re-running your ICD10s? 

Thanks again Lauric.

Luke

**Comment by LauricF** [comment]
it works perfectly, thank you Luke
